version: '3.3'

services:

  api:
    build: api
    volumes:
      - ./api:/var/www/api:delegated
      - ./api/vendor:/var/www/api/vendor:delegated
    ports:
      - 9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
      - redis
      - phpmyadmin
      - mail
      - swagger
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.TODO.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "--entrypoints.web.address=:8080"

  swagger:
    build: swagger
    ports:
      - 9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./swagger:/var/www/swagger:delegated
      - ./api/controllers:/var/www/controllers:delegated
      - ./api/envs:/var/www/envs:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swagger.rule=Host(`swagger.TODO.localhost`)"
      - "traefik.http.routers.swagger.entrypoints=web"
      - "--entrypoints.web.address=:8081"

  app:
    build: app
    volumes:
      - ./app:/usr/src/app:delegated
      - ./app/node_modules:/usr/src/app/node_modules:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`TODO.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "--entrypoints.web.address=:4200"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: TODO
      MONGO_INITDB_ROOT_PASSWORD: TODO

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: TODO
      ME_CONFIG_MONGODB_ADMINPASSWORD: TODO
      ME_CONFIG_MONGODB_URL: mongodb://TODO:TODO@mongo:27017/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo_express.rule=Host(`mongo.TODO.localhost`)"
      - "traefik.http.routers.mongo_express.entrypoints=web"
      - "traefik.http.routers.mongo_express.service=mongo_express"
      - "traefik.http.services.mongo_express.loadbalancer.server.port=8081"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: TODO
      MYSQL_DATABASE: TODO
      MYSQL_USER: TODO
      MYSQL_PASSWORD: TODO
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: TODO
      PMA_PASSWORD: TODO
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.TODO.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "--entrypoints.web.address=:80"

  redis:
    image: redis:alpine

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=TODO:redis:6379
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis_commander.rule=Host(`redis.TODO.localhost`)"
      - "traefik.http.routers.redis_commander.entrypoints=web"
      - "traefik.http.routers.redis_commander.service=redis_commander"
      - "traefik.http.services.redis_commander.loadbalancer.server.port=8081"

  mail:
    user: root
    image: mailhog/mailhog
    ports:
      - "1025:1025"
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./mailhog:/maildir
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.TODO.localhost`)"
      - "traefik.http.routers.mail.entrypoints=web"
      - "traefik.http.routers.mail.service=mail"
      - "traefik.http.services.mail.loadbalancer.server.port=8025"

  traefik:
    image: "traefik:v2.2"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=HostRegexp(`traefik.TODO.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "--entrypoints.api.address=:80"
