version: '3.3'

services:

  api:
    build: api
    volumes:
      - ./api:/var/www/api:delegated
      - ./api/vendor:/var/www/api/vendor:delegated
    ports:
      - "9003"
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql
      - redis
      - phpmyadmin
      - mail

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: TODO
      MYSQL_DATABASE: TODO
      MYSQL_USER: TODO
      MYSQL_PASSWORD: TODO
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: TODO
      PMA_PASSWORD: TODO

  redis:
    image: redis:alpine

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=TODO:redis:6379
    depends_on:
      - redis

  mail:
    user: root
    image: mailhog/mailhog
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./mailhog:/maildir
    ports:
      - "1025:1025"
      - "8025:8025"
